ANDROID: Fix !CONFIG_DMA_SHARED_BUFFER build failure
Commit 13beada2dac3 ("ANDROID: Don't use current pointer for
per-process dmabuf accounting") changed the argument type for
dma_buf_account_task, dma_buf_unaccount_task, and put_dmabuf_info but
did not update the corresponding no-op implementations in the
!CONFIG_DMA_SHARED_BUFFER section, causing build warnings:

1 warning generated.
common/mm/mmap.c:152:13: error: incompatible pointer types passing 'struct task_dma_buf_info *' to parameter of type 'struct task_struct *' [-Werror,-Wincompatible-pointer-types]
                                               vma->vm_mm->dmabuf_info);
                                               ^~~~~~~~~~~~~~~~~~~~~~~
common/include/linux/dma-buf.h:826:28: note: passing argument to parameter 'task' here
                                          struct task_struct *task) {}

Fixes: 13beada2dac3 ("ANDROID: Don't use current pointer for per-process dmabuf accounting")
Bug: 457281015
Bug: 461520624
Bug: 465344738
Bug: 467225441
Change-Id: I727105e230b6b537f7b3621c5aabb1012640f416
Signed-off-by: T.J. Mercier <tjmercier@google.com>